portfolio/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('posts/', views.post_list, name='list')
]

portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# import views
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('projects/', include('projects.urls', namespace='projects')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.projects_index_view, name='project_index'),
    path('page/<slug:slug>', views.projects_detail_view, name='project_detail'),
]

portfolio/blog/models.py
from django.db import models

# import User
from django.contrib.auth.models import User

# import slugify
from django.utils.text import slugify

# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length=30, default='uncategorized')

class Posts(models.Model):
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField('Category' ,related_name='posts')
    slug = models.SlugField(editable=False, blank=True, unique=True)
    cover = models.ImageField(blank=True, null=True, upload_to='media_cover_posts/')

    class Meta:
        ordering = [
            '-created_on'
        ]

    def save(self):
        self.slug = slugify(self.title)
        super().save()

    def __str__(self):
        return "{} ".format(self.title)

portfolio/projects/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=50)
    url = models.URLField(max_length=200, blank=True)
    slug = models.SlugField(blank=True, editable=False, unique=True)
    image = models.ImageField(blank=True, null=True, upload_to='project_img/')

    def save(self):
        self.slug = slugify(self.title)
        super().save()

    def __str__(self):
        return "{}. {}".format(self.id, self.title)

portfolio/blog/views.py
from django.shortcuts import render

# Create your views here.
def post_list(request):
    pass

portfolio/personal_portfolio/views.py
from django.shortcuts import render

def index(request):
    context = {
        'title':'Portfolio Page',
    }

    return render(request, 'index.html', context)

portfolio/projects/views.py
from django.shortcuts import render

# import models
from .models  import Project

# Create your views here.

def projects_index_view(request):
    projects = Project.objects.all()
    context = {
        'projects': projects,
        'title': 'Project List Page',
    }

    return render(request, 'projects/project_index.html', context)


def projects_detail_view(request,slug):
    project = Project.objects.filter(slug=slug)

    context = {
        'project': project,
    }

    return render(request, 'projects/project_detail.html', context)

portfolio/projects/templates/projects/project_detail.html
{% extends "base.html" %}

{% block page_title %}
  {% for project in project %}
      {{project.title}}
  {% endfor %}

{% endblock page_title %}

{% block contents %}
{% for project in project %}
<div class="container" style="margin-top: 75px;">
  <div class="row">
    <div class="col-md-8">
      <img src="{{project.image.url}}" alt="{{project.title}}" style="width:100%">
    </div>
    <div class="col-md-4">
      <h4>About The Project: </h4>
      <p class="lead">{{project.description}}</p>
      <br>
      <h4>Technology used: </h4>
      <p class="lead">{{project.technology}}</p>
      <h4>Sources</h4>
      <a href="{{project.url}}" class="lead">View Sources</a>
    </div>
  </div>
</div>
{% endfor %}

{% endblock contents %}

portfolio/projects/templates/projects/project_index.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
  {{title}}
{% endblock page_title %}

{% block contents %}
  <link rel="stylesheet" href="{% static "assets/css/project_index.css" %}">
  <h1>{{title}}</h1>
  <div class="container">
    <div class="row">
      {% for project in projects %}
        <div class="col-md-4">
          <div class="card mb-2">
            <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top">
            <div class="card-body">
              <h5 class="card-title">{{project.title}}</h5>
              <p class="card-text">{{project.description |slice:52}}</p>
              <a href="{% url 'projects:project_detail' project.slug %}" class="btn btn-outline-primary">Read More</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock contents %}

portfolio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      {% block page_title %}
        {# write your page title here #}
      {% endblock page_title %}
    </title>
    <link rel="stylesheet" href="{% static 'assets/css/base_style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  </head>
  <body>
    {# navbar #}
    <nav class="navbar navbar-expand-md bg-dark text-uppercase fixed-top" id="mainNav">
      <div class="container">
        <a href="{% url 'index' %}" class="navbar-brand js-scroll-trigger text-white">My Profile</a>
        <button class="navbar-toggler navbar-toggler-right font-weight-bold bg-secondary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu</button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-md-1">
              <a href="{% url 'projects:project_index' %}" class="nav-link py-3 px-md-3 rounded js-scroll-trigger">Project</a>
            </li>
            <li class="nav-item mx-0 mx-md-1">
              <a href="#" class="nav-link py-3 px-md-3 rounded js-scroll-trigger">Blog</a>
            </li>
            <li class="nav-item mx-0 mx-md-1">
              <a href="#" class="nav-link py-3 px-md-3 rounded js-scroll-trigger">Contacts</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {# akhir navbar #}

    {% block contents %}
      {# write your contents here #}
    {% endblock contents %}

    {# footer #}
      {# tinggal bikin footer aja hwhwhwh #}

    {# jquery popper dan bootstrap #}
    <script src="{% static "assets/jquery/jquery.slim.min.js" %}"></script>
    <script src="{% static "assets/popper/popper.min.js" %}"></script>
    <script src="{% static "assets/bootstrap/js/bootstrap.min.js" %}"></script>
  </body>
</html>

portfolio/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
  {{title}}
{% endblock page_title %}

{% block contents %}
{# load static #}
<link rel="stylesheet" href="{% static "assets/css/style.css" %}">

<header class="masthead bg-light text-dark text-center">
  <div class="jumbotron jumbotron-fluid">
    {# img profile avatar #}
    <img src="/media/profile/profile.jpg" alt="" class="masthead-avatar mb-2 rounded-circle">
    {# pengaturan heading #}
    <h1 class="masthead-heading text-uppercase display-4">Feri Lukmansyah</h1>

    {# pengaturan subheading #}
    <p class="masthead-subheading font-weight-light lead">Python Developer | Linux Sysadmin | Content Creator</p>
  </div>
</header>

{# pembagian sesi #}

{# sesi About #}
<section class="page-section mb-0" id="about">
  <div class="container">
    <h2 class="page-section-heading text-center">Something About Me</h2>


    <div class="divider-custom divider-light">
      <div class="custom-line"></div>
      <div class="custom-line"></div>
    </div>

    {# content About #}
    <div class="row">
      <div class="col-md-5 ml-auto">
        <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis minus dolorum pariatur laboriosam. Ipsum nemo porro officia eius sint sapiente aliquid exercitationem voluptatem hic, architecto minus maxime minima nisi. Officia!</p>
      </div>
      <div class="col-md-5 mr-auto">
        <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis minus dolorum pariatur laboriosam. Ipsum nemo porro officia eius sint sapiente aliquid exercitationem voluptatem hic, architecto minus maxime minima nisi. Officia!</p>
      </div>
    </div>
  </div>
</section>


{# Contacts section #}

<section class="page-section mb-0" id="contact" style="background-color: #e3f2fd">
  <div class="container">
    <h2 class="page-section-heading text-center">Contacts Me @</h2>

    {# icon divider #}

    <div class="divider-custom divider-light">
      <div class="custom-line"></div>
      <div class="custom-line"></div>
    </div>

    {# content Contacts #}
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Telegram</h5>
            <p class="card-text">Hey, I'm using Telegram you can found me here</p>
            <a href="#" class="card-link">Go Contact Me !</a>
          </div>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Linked In</h5>
            <p class="card-text">Hey, I'm using Linkedin you can see my Profile here</p>
            <a href="#" class="card-link">See My Profile</a>
          </div>
        </div>
      </div>

  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Facebook</h5>
        <p class="card-text">Hey, you can Found me in Facebook</p>
        <a href="#" class="card-link">See My Facebook</a>
      </div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Github</h5>
        <p class="card-text">I'm using Github to Push My projects Go to <a href="#">Project page to detail</a></p>
        <a href="https://github.com/perymerdeka/" class="card-link">See Sources</a>
      </div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Youtube</h5>
        <p class="card-text">you also can watch a some tutorial video at Youtube</p>
        <a href="#" class="card-link">Go watch</a>
      </div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Website Tutorial</h5>
        <p class="card-text">Hey, you can read tutorial in <a href="">my Blog</a> or </p>
        <a href="https://kodelinux.web.id" class="card-link">Read here</a>
      </div>
    </div>
  </div>

</div>
  </div>
</section>

{% endblock contents %}